language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules

# 设置环境变量
env:
  matrix:
    - CI=true

script:
  # 默认运行编译脚本
  - npm run build-storybook

deploy:
  # 发布到 gh-pages 上
  - provider: script
    # Do not delete the build assets
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      # 当 master 有 push 的时候，触发 deploy 操作
      branch: master
  # 发布到 npm 上
  - provider: npm
    skip_cleanup: true
    email: aisi@mail.i-i.ai
    api_key:
      secure: HAUyQgZD+OZEeSg0mXHAbkWgjlw1v9FiAwrc7BSP0sMFhmb+4q1NDyHGU/XvBhHgkaUNfqV6bNuIWoL2OD5rn4gpKVbwdUGA57Xok+nFcL7UpiZqwiA88p+nPl7pXzo1HDR66p3CNsOrK/CIRGlmqaJ/ot1sdVnZXImPojHJwgDIkJTwIevF62kNMqbAQLcNVuHUB/0JWAQwyg95lXElVjV2mWYYQBs6kyKWNq+0wkfmcYGmimYLYp7vV3yDr069XwKiRq1XOKlNaTTZHMkzzfrC+uhLwKfm8XnRWMfj/hQmMp5ELQanezq81zTBqDM8uvBwguQdCInp7ligrAv3Krc+M7i9RxzpgUwz5UjARtjkthjvPnM8T9Ga9uXSZs+dnuiEyYaypm0xrMBDGpC9hRQxlCO2Nv9pWcA42wErBYW+z1YHDAYnDSFSKkkBeqr5s8xDxwUkJDupsab9OPJBHXIgbdSrOmwATtM2peiZ7p1O38vMgzs1v4eWV2ZTExJ4KIixupPYEOZv75cTSv5taps+hz5zDVeAZIWdzxu5Q73kf2Gq9ARtR5az//FbLdOUcAp7+fdn6ry5G85jHb7b8APKiWOTlUdC7LtIbY9DWq4EixDK88yqGNYdDt4hqHRiv7tp+gissCjsu61h4tTV7eFt37wO0Y9rS8GiI6A9uUg=
    on:
      branch: master
      repo: LagrangeLabs/ii-admin-ui
